cluster:
  network:
    podSubnets:
      - "10.42.0.0/16"
      - "2001:67c:1104:d000::/56"
    serviceSubnets:
      - "10.43.0.0/16"
      - "2001:67c:1104:e03e::/112"
    cni:
      name: none
  proxy:
    disabled: true
