apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:HJ0BztzAQVESE/w638ht0W090cSc10sGKBbm4Wqz0NK4/IwM,iv:yZWo9obgVcgFkua8tZJTFcIq0JXAvEb4RKeqR6p7WQ4=,tag:3p4pmnv4NHzHi+N8eMgECA==,type:str]
    credentials.json: ENC[AES256_GCM,data:AxUbt86cO2V7DxSbP60matZZFYmFg6cBp3YGCeS3s1Ho9KOWpTutL3bwqpN7oB+l3qeTm2ldbl4ue2OpVFIGJ4+yeSyrZsW4hupLZ+vvym2X3i+kcqK1QZ/dkDtPqvAwnFqXvdJ+xBjncMCuRPTb2BugT3LFvtGcWHUama+dhFqJcrV1w/0NjE9aB5ua3PdopzDH2++JYnzzqBy8f2OqsGJTH3X22xaJSgPzmfS3og==,iv:pEPq2uMUre9fyWukZZwoIwjfzuZHfY6FW2AN7z+4r+I=,tag:g8i+3rBL+ACPonO064D/sw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kyu4t3wc94687gy4pw58jdnftckwh2ewpnqrqd2jvu9wvwa3sf3qywmgap
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArOGg4QWFvNmVqNGFxQ0FN
            RkZNdGd5aGN5ZEF1K1pYU1grMVhTTi84bGtZCkEwMXgxd2Zma1FYWG9iT042a3dE
            VGk2UjJrdERmUGc5N2RaQnlOLzkwVUUKLS0tIFZURGNFTDNsU2Myc000bDEvaUlh
            eDI2Z3RZL1lLQzVEN01wLzRpYkhQcmsKY0n00j0EnWHBDXzqBpQmZI/thaS3QgUt
            CDDxiPhfHgXpYWrMDxDT4lc1x5W1WH49BOdIg2QvfLKBjWKpclV3nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-17T04:38:35Z"
    mac: ENC[AES256_GCM,data:4psKNvQtGfsaY9jhRB0wlA1LgQcxTUJMqFq9USRzJa6RuiVfrVE9hikCaq2p9YqLV24uDa4fV/E6pjrvqqHTKFn9fEQzOOxNGY8OUgGGiMWF3DXA1tYCPJFFnjDJT/QIYb17X8fOoBDJlYPYpGZAyxLZsPPPBT3Sj/Zh1ZutH/k=,iv:lkLUkBW2OCxUGCXqIt2wqWGWXd4E6FHC+TQF/8NwGFc=,tag:I/HeW8RUDlenLE2CB1t62A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
